# Server01  IF Datei

- hosts: server01
  name: Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4
      copy: 
        src: /home/cumulus/ON-02/server01-01 
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for Server01
      shell: /sbin/ifreload -a

# Server02 IF Datei

- hosts: server02
  name: Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4
      copy: 
        src: /home/cumulus/ON-02/server02-01
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for Server02
      shell: /sbin/ifreload -a

# #################################################################
# #################################################################
# #################################################################

# Leaf01 IF Datei

- hosts: leaf01
  name: Interfaces for Leaf01
  become: yes
  gather_facts: no
  tasks:
    - name: bridge access-port and l3-uplink
      copy: 
        src: /home/cumulus/ON-02/leaf01-if-01 
        dest: /etc/network/interfaces
    # aktivieren
    - name: Activate changes
      shell: /sbin/ifreload -a
      
# Leaf01 routing      
      
- hosts: leaf01
  name: Routing
  become: yes
  gather_facts: no
  tasks:
    - name: simple MP-BGP
      copy:
        src: /home/cumulus/ON-02/leaf01-frr-01
        dest: /etc/frr/frr.conf
      notify:
        - frr_reload

  handlers:
    - name: frr_reload
      service:
        name=frr
        state=reloaded
      listen: "frr_reload"
    
# #################################################################    
    
# Leaf02 IF Datei

- hosts: leaf02
  name: Interfaces for Leaf02
  become: yes
  gather_facts: no
  tasks:
    - name: bridge access-port and l3-uplink 
      copy: 
        src: /home/cumulus/ON-02/leaf02-if-01 
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes
      shell: /sbin/ifreload -a    
    
# Leaf02 routing   
      
- hosts: leaf02
  name: Routing
  become: yes
  gather_facts: no
  tasks:
    - name: simple MP-BGP
      copy: 
        src: /home/cumulus/ON-02/leaf02-frr-01
        dest: /etc/frr/frr.conf
      notify:
        - frr_reload
        
  handlers:
    - name: frr_reload
      service:
        name=frr
        state=reloaded
      listen: "frr_reload"
      
# #################################################################    
    
# Leaf03 IF Datei

- hosts: leaf03
  name: Interfaces for Leaf03
  become: yes
  gather_facts: no
  tasks:
    - name: bridge access-port and l3-uplink 
      copy: 
        src: /home/cumulus/ON-02/leaf03-if-01 
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes
      shell: /sbin/ifreload -a    
    
# Leaf03 routing   
      
- hosts: leaf03
  name: Routing
  become: yes
  gather_facts: no
  tasks:
    - name: simple MP-BGP
      copy: 
        src: /home/cumulus/ON-02/leaf03-frr-01
        dest: /etc/frr/frr.conf
      notify:
        - frr_reload
        
  handlers:
    - name: frr_reload
      service:
        name=frr
        state=reloaded
      listen: "frr_reload"
 
# #################################################################  
 
# Spine01 IF Datei

- hosts: spine01
  name: Interfaces for Spine01
  become: yes
  gather_facts: no
  tasks:
    - name: l3-fabric 
      copy: 
        src: /home/cumulus/ON-02/spine01-if-01 
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes
      shell: /sbin/ifreload -a   
 
# Spine01 routing
      
- hosts: spine01
  name: Routing
  become: yes
  gather_facts: no
  tasks:
    - name: simple MP-BGP
      copy: 
        src: /home/cumulus/ON-02/spine01-frr-01
        dest: /etc/frr/frr.conf
      notify:
        - frr_reload
      
  handlers:
    - name: frr_reload
      service:
        name=frr
        state=reloaded
      listen: "frr_reload"
