# Server01  IF Datei

- hosts: server01
  name: Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4
      copy: 
        src: /home/cumulus/ON-02/server01-02-C
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for Server01
      shell: /sbin/ifreload -a

# Server02 IF Datei

- hosts: server02
  name: Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4
      copy: 
        src: /home/cumulus/ON-02/server02-02-C
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for Server02
      shell: /sbin/ifreload -a
      
    # warten
    - name: wait after ifreload
      pause:
        seconds: 5
      
    # Workaorund
    - name: bonding 1
      shell: /sbin/ifdown uplink
      
    - name: wait after ifdown
      pause:
        seconds: 3
      
    - name: bonding 2
      shell: /sbin/ifup uplink
      
    - name: wait after ifup
      pause: 
        seconds: 3
      
# #################################################################
# #################################################################
# #################################################################

# Leaf01 IF Datei

- hosts: leaf01
  name: Interfaces of Leaf01
  become: yes
  gather_facts: no
  tasks:
    - name: SVI and VRR for Leaf01
      copy: 
        src: /home/cumulus/ON-02/leaf01-if-02-C
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for Leaf01
      shell: /sbin/ifreload -a
      
# Leaf01 routing      
      
- hosts: leaf01
  name: Routing
  become: yes
  gather_facts: no
  tasks:
    - name: simple MP-BGP
      copy:
        src: /home/cumulus/ON-02/leaf01-frr-02-C
        dest: /etc/frr/frr.conf
      notify:
        - frr_reload
        
  handlers:
    - name: frr_reload
      service:
        name=frr
        state=reloaded
      listen: "frr_reload"



# #################################################################    
    
# Leaf02 IF Datei

- hosts: leaf02
  name: Interfaces for Leaf02
  become: yes
  gather_facts: no
  tasks:
    - name: SVI and VRR for Leaf02
      copy: 
        src: /home/cumulus/ON-02/leaf02-if-02-C 
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for leaf02
      shell: /sbin/ifreload -a    
    
# Leaf02 routing   
      
- hosts: leaf02
  name: Routing
  become: yes
  gather_facts: no
  tasks:
    - name: simple MP-BGP
      copy: 
        src: /home/cumulus/ON-02/leaf02-frr-02-C
        dest: /etc/frr/frr.conf
      notify:
        - frr_reload
        
  handlers:
    - name: frr_reload
      service:
        name=frr
        state=reloaded
      listen: "frr_reload"
      
# #################################################################    
    
# Leaf03 IF Datei

- hosts: leaf03
  name: Interfaces for Leaf03
  become: yes
  gather_facts: no
  tasks:
    - name: SVI and VRR for Leaf03
      copy: 
        src: /home/cumulus/ON-02/leaf03-if-02-C 
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for leaf03
      shell: /sbin/ifreload -a    
    
# Leaf03 routing   
      
- hosts: leaf03
  name: Routing
  become: yes
  gather_facts: no
  tasks:
    - name: simple MP-BGP
      copy: 
        src: /home/cumulus/ON-02/leaf03-frr-02-C
        dest: /etc/frr/frr.conf
      notify:
        - frr_reload
        
  handlers:
    - name: frr_reload
      service:
        name=frr
        state=reloaded
      listen: "frr_reload"
 
# #################################################################  
 
# Spine01 IF Datei

- hosts: spine01
  name: Interfaces for Spine01
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4 und BGP 
      copy: 
        src: /home/cumulus/ON-02/spine01-if-02-C 
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes
      shell: /sbin/ifreload -a   
 
# Spine01 routing
      
- hosts: spine01
  name: Routing
  become: yes
  gather_facts: no
  tasks:
    - name: simple MP-BGP
      copy: 
        src: /home/cumulus/ON-02/spine01-frr-02-C
        dest: /etc/frr/frr.conf
      notify:
        - frr_reload
        
  handlers:
    - name: frr_reload
      service:
        name=frr
        state=reloaded
      listen: "frr_reload"
