# sudo apt update
# sudo apt install redis-server
# sudo nano /etc/redis/redis.conf !systemd
# sudo apt install python-pip
# pip install redis

#  https://github.com/CumulusNetworks/python-nlmanager

- hosts: server01
  name: setup git, pip, netlink, ngrok, redis
  become: yes
  tasks:

    - name: Installieren git
      apt:
        name: git
        state: present

    - name: Installieren pip
      apt:
        name: python-pip
        state: present
        
    - name: Installieren netlink
      command: "pip install nlmanager"
      args:
        chdir: /home/cumulus

    - name: Installieren ngrok
      shell: curl -O https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

    - name: entpacken vorbereiten
      apt:
        name: unzip
        state: present

    - name: Auspacken
      shell: unzip -o /home/cumulus/ngrok-stable-linux-amd64.zip  
      
    - name: Installieren redis
      apt:
        name: redis
        state: present

        
        
